version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: 1014
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - postgres_db
    volumes:
      - static_volume:/app/static
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    container_name: nginx_server
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static

volumes:
  postgres_data:
  static_volume:
