# Generated by Django 5.1.7 on 2025-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantinfo",
            name="address",
            field=models.CharField(
                default="Не указан", max_length=255, verbose_name="Адрес"
            ),
        ),
    ]
